### PR TITLE
Fixes for target VPC Peering route table handling

### PR DESCRIPTION
**Pull request by bbaptist**
This fixes the VPC Peering Connection leaving a stale route in the target VPC when removing the source VPC

### CODE REVIEW

**Comment by bbaptist** [comment]
@EarthmanT Any chance you could check this out and see if it can be merged?

**Comment by bbaptist** [comment]
3 releases later and I still have to maintain this patch in my custom AWS plugin to have working VPC Peering.

**Comment by EarthmanT** [comment]
Hi thanks! (Merged), Sorry for the long wait! Also, please checkout the next version of the [AWS Plugin](https://github.com/cloudify-incubator/cloudify-awssdk-plugin/releases).

**Comment by bbaptist** [comment]
Sounds great, will do. Thank you very much,

**Pull request merged**
